services:
  palworld:
    build: ./docker
    container_name: pps
    stop_grace_period: ${PALWORLD_GRACEPERIOD}
    restart: ${PALWORLD_RESTARTTYPE}
    image: palworld-proton
    volumes:
      # mount directory for storing logs & backups
      - ./data/logs:/app/logs 
      - ./data/backups:/app/backups
      - ./data/logs/steam:/home/steam/.steam/steam/logs # add steam logs
      # mount the actual game server folder
      - ./data/palworld:/app/PalServer
      # additional mounts for system id + time
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      # palworld: main server communication line 
      - ${PALWORLD_GAME_PORT}:8211/udp 
      # palworld: allows server to show up in the community servers tab 
      - ${PALWORLD_COMM_PORT}:27015/tcp 
      # palworld: allows rcon to communicate with server
      - ${PALWORLD_RCON_PORT}:25575/tcp
      # Palworld: rest api port
      - ${PALWORLD_REST_PORT}:8212/tcp 
    env_file:
      - .env
